fn main() {
    // The webview navigates to the sidecar's http origin after readiness, so
    // every custom command is invoked from a *remote* page. Remote origins
    // are checked against the ACL even for app commands: without an
    // autogenerated app manifest the invoke is rejected with
    // "Command ... not allowed by ACL". This registers the shell's custom
    // commands so `allow-*` permissions exist and can be granted in
    // capabilities/main.json.
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(&[
                "ui_ready",
                "desktop_info",
                "list_diagnostics",
                "run_diagnostic",
                "spawn_pty",
                "write_pty",
                "kill_pty",
            ])),
    )
    .expect("failed to run tauri-build");
}
